# Generated by Django 3.2.7 on 2022-06-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20220629_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='account',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='account',
        ),
    ]
