# Generated by Django 3.2.7 on 2022-06-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_shop_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
