# Generated by Django 3.2.7 on 2022-06-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='shop',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.shop'),
            preserve_default=False,
        ),
    ]
