# Generated by Django 3.2.7 on 2022-06-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_ver_account_verified'),
        ('listings', '0018_alter_listing_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPreUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField(verbose_name='Listing_id')),
                ('title', models.CharField(max_length=140, verbose_name='Title')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(max_length=4000, verbose_name='Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, default=None, max_length=20, verbose_name='Shop')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
    ]
