# Generated by Django 3.2.7 on 2022-06-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_competitor_listingpreuploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_connection',
        ),
    ]
