# Generated by Django 3.2.7 on 2022-06-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20220629_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False)),
                ('favorites', models.IntegerField(verbose_name='Number of Likes on date')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='ListingSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False)),
                ('sales', models.IntegerField(verbose_name='Number of Sales on date')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.competitor')),
            ],
        ),
        migrations.RemoveField(
            model_name='listingpreuploaded',
            name='account',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_etsy',
            field=models.BooleanField(default=False, verbose_name='True=on Etsy, False=pre-uploaded'),
        ),
        migrations.DeleteModel(
            name='CompetitorTopSales',
        ),
        migrations.DeleteModel(
            name='ListingPreUploaded',
        ),
        migrations.AddField(
            model_name='listingsales',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
