# Generated by Django 4.0.4 on 2022-07-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20220630_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.AddField(
            model_name='listing',
            name='category_id',
            field=models.IntegerField(blank=True, default=None, verbose_name='Category id'),
        ),
        migrations.AddField(
            model_name='listing',
            name='currency_code',
            field=models.CharField(blank=True, default=None, max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_customizable',
            field=models.BooleanField(default=False, verbose_name='Is customizable?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='is_supply',
            field=models.BooleanField(default=False, verbose_name='Is supply?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='listing',
            name='materials',
            field=models.CharField(blank=True, default=None, max_length=300, verbose_name='Materials'),
        ),
        migrations.AddField(
            model_name='listing',
            name='occasion',
            field=models.CharField(blank=True, default=None, max_length=300, verbose_name='Occasion'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo10',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Photo10'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo2',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Photo2'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo3',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Photo3'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo4',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Photo4'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo5',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Photo5'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo6',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Photo6'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo7',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Photo7'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo8',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Photo8'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo9',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Photo9'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Main Photo'),
        ),
        migrations.AddField(
            model_name='listing',
            name='primary_variation',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Primary Variation'),
        ),
        migrations.AddField(
            model_name='listing',
            name='secondary_variation',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Primary Variation'),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_template_id',
            field=models.IntegerField(blank=True, default=None, verbose_name='Shipping Template id'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=32, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=40, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=300, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='listing',
            name='taxonomy_id',
            field=models.IntegerField(blank=True, default=None, verbose_name='Taxonomy id'),
        ),
        migrations.AddField(
            model_name='listing',
            name='when_made',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='When made?'),
        ),
        migrations.AddField(
            model_name='listing',
            name='who_made',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Who made?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.IntegerField(blank=True, default=None, verbose_name='Listing_id on Etsy'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=140, verbose_name='Title'),
        ),
    ]
