# Generated by Django 4.0.4 on 2022-07-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0016_alter_filelistinguploader_file'),
        ('listings', '0024_remove_listing_photo_listing_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='primary_variation',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primary_variation', to='uploader.variation', verbose_name='Primary Variation'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='secondary_variation',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_variation', to='uploader.variation', verbose_name='Secondary Variation'),
        ),
    ]
