# Generated by Django 4.0.4 on 2022-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_listing_primary_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(blank=True, default=None, verbose_name='Quantity'),
        ),
    ]
