# Generated by Django 4.0.4 on 2022-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_listing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Category id'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Listing_id on Etsy'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='shipping_template_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Shipping Template id'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='taxonomy_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Taxonomy id'),
        ),
    ]
