# Generated by Django 4.0.4 on 2022-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_alter_listing_category_id_alter_listing_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_customizable',
            field=models.BooleanField(null=True, verbose_name='Is customizable?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_supply',
            field=models.BooleanField(null=True, verbose_name='Is supply?'),
        ),
    ]
