# Generated by Django 4.0.4 on 2022-07-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_alter_listing_primary_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency_code',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=2, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='materials',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Materials'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='occasion',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Occasion'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo10',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo10'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo4'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo5'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo6'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo7'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo8',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo8'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo9',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Photo9'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=140, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='when_made',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='When made?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='who_made',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Who made?'),
        ),
    ]
