# Generated by Django 4.0.4 on 2022-07-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_listing_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo10',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Photo10'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo2',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo3',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo4',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Photo4'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo5',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Photo5'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo6',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Photo6'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo7',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Photo7'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo8',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Photo8'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo9',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Photo9'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Main Photo'),
        ),
    ]
