# Generated by Django 3.2.7 on 2022-06-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_etsy', models.CharField(max_length=25, verbose_name='Name for Etsy')),
                ('name_app', models.CharField(max_length=25, verbose_name='Name for App')),
            ],
        ),
        migrations.CreateModel(
            name='VariationOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=25, verbose_name='Option')),
                ('SKU', models.IntegerField(verbose_name='SKU')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.variation')),
            ],
        ),
    ]
