# Generated by Django 3.2.7 on 2022-06-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_ver_account_verified'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='account',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, to='main.account'),
            preserve_default=False,
        ),
    ]
