# Generated by Django 3.2.7 on 2022-06-30 14:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_staticphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticphoto',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[800, 600], upload_to='images/static'),
        ),
    ]
