# Generated by Django 3.2.7 on 2022-06-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_staticphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticphoto',
            name='photo',
            field=models.ImageField(blank=True, default=True, upload_to='images/static', verbose_name='Photo'),
        ),
    ]
