# Generated by Django 3.2.7 on 2022-06-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_ver_account_verified'),
        ('uploader', '0005_alter_staticphoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='SmartStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.JSONField()),
                ('archive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploader.smartarchive')),
            ],
        ),
    ]
