# Generated by Django 3.2.7 on 2022-06-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_smartarchive_smartstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartarchive',
            name='file',
            field=models.FileField(default=1, upload_to='archives'),
            preserve_default=False,
        ),
    ]
