# Generated by Django 3.2.7 on 2022-07-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_alter_smartstructure_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartstructure',
            name='structure',
            field=models.JSONField(verbose_name='Json Structure'),
        ),
    ]
