# Generated by Django 3.2.7 on 2022-07-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_alter_smartstructure_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name this template')),
                ('separation', models.IntegerField(verbose_name='Method of separation')),
                ('title', models.CharField(max_length=140, verbose_name='Template for title')),
                ('photo1', models.CharField(max_length=500, verbose_name='Photo1')),
                ('photo2', models.CharField(max_length=500, verbose_name='Photo2')),
                ('photo3', models.CharField(max_length=500, verbose_name='Photo3')),
                ('photo4', models.CharField(max_length=500, verbose_name='Photo4')),
                ('photo5', models.CharField(max_length=500, verbose_name='Photo5')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.smartstructure')),
                ('variation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.variation')),
            ],
        ),
    ]
