# Generated by Django 3.2.7 on 2022-07-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0012_smarttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='smarttemplate',
            name='separation_number',
            field=models.IntegerField(default=1, verbose_name='Separation number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smarttemplate',
            name='separation',
            field=models.CharField(max_length=500, verbose_name='Method of separation'),
        ),
    ]
