# Generated by Django 3.2.7 on 2022-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0013_auto_20220708_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smarttemplate',
            name='photo1',
            field=models.CharField(blank=True, max_length=500, verbose_name='Photo1'),
        ),
        migrations.AlterField(
            model_name='smarttemplate',
            name='photo2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='smarttemplate',
            name='photo3',
            field=models.CharField(blank=True, max_length=500, verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='smarttemplate',
            name='photo4',
            field=models.CharField(blank=True, max_length=500, verbose_name='Photo4'),
        ),
        migrations.AlterField(
            model_name='smarttemplate',
            name='photo5',
            field=models.CharField(blank=True, max_length=500, verbose_name='Photo5'),
        ),
    ]
