# Generated by Django 4.0.4 on 2022-07-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_ver_account_verified'),
        ('uploader', '0014_auto_20220709_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileListingUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('file', models.FileField(upload_to='upload_listing_files', verbose_name='File')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
    ]
