# Generated by Django 4.0.4 on 2022-07-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0017_alter_staticphoto_photo_dynamicphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicphoto',
            name='archive',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.smartarchive', verbose_name='Name of Archive, Manually uploaded is empty'),
        ),
        migrations.AlterField(
            model_name='dynamicphoto',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Name for App your photo'),
        ),
    ]
