# Generated by Django 3.2.7 on 2022-05-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribtion',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='Subscribtion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_connection',
            field=models.BooleanField(default=False, verbose_name='Shop Connetion'),
        ),
    ]
