# Generated by Django 3.2.7 on 2022-05-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220501_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.AddField(
            model_name='user',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payment'),
        ),
    ]
