# Generated by Django 3.2.7 on 2022-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220510_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='shop_name',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Shop'),
        ),
    ]
