# Generated by Django 3.2.7 on 2022-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_account_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='shop_name',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Shop'),
        ),
    ]
