# Generated by Django 3.2.7 on 2022-05-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_account_ver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ver',
            new_name='verified',
        ),
    ]
